### ISSUE TITLE
possible regex bug

### ISSUE THREAD

**Issue by CianMurphy** [An7ar35/genomeMaker#1]
not tested for all options but -p does not allow underscores: 

Invalid value 'my_genome': File name must be composed of only letter/numbers with no extension.
[20/11/2016, 16:09:36] Cian Murphy: Value 'my_genome' for Option '-p' is not valid.

'genome' works fine though.

**Comment by An7ar35** [comment]
Regex for pipeline parser option should be fixed now. Modified to ````(_?[0-9a-zA-Z]+_?)+)````: must have at least an alphanumeric character (````[0-9a-zA-Z]+````) surrounded optionally by underscores (````_?````). I.e. allows stuff like ````_my_genome_```` or ````my_genome```` but not ````____````.

Done with a little help with [Regexr.com](http://regexr.com/)
